services:
  kafka:
    image: redpandadata/redpanda:v24.1.3
    command: [
      "redpanda", "start",
      "--overprovisioned", "--smp", "1",
      "--reserve-memory", "0M",
      "--node-id", "0",
      "--kafka-addr", "PLAINTEXT://0.0.0.0:9092",
      "--advertise-kafka-addr", "PLAINTEXT://kafka:9092"
    ]
    ports: ["9092:9092"]

  flink-jobmanager:
    image: flink:1.18.1-scala_2.12
    volumes:
      - ./flink_job:/opt/flink/job
    command: |
      bash -c "
      echo 'Iniciando JobManager...';
      /docker-entrypoint.sh jobmanager &
      JOBMANAGER_PID=$!
      
      echo 'Esperando 15s para que el cluster inicie...';
      sleep 15;
      
      echo 'Instalando dependencias de PyFlink...';
      pip install -r /opt/flink/job/requirements.txt;
      
      echo 'Enviando trabajo de Flink (app.py)...';
      flink run -py /opt/flink/job/app.py;
      
      wait $JOBMANAGER_PID
      "
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
      - BOOTSTRAP_SERVERS=kafka:9092
      - SCORE_THRESHOLD=0.62
      - TOPIC_INPUT=questions.answers
      - TOPIC_OUTPUT_VALIDATED=questions.validated
      - TOPIC_OUTPUT_REGENERATE=questions.llm
    ports: ["8081:8081"]
    depends_on: [kafka]

  flink-taskmanager:
    image: flink:1.18.1-scala_2.12
    volumes:
      - ./flink_job:/opt/flink/job
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    depends_on: [flink-jobmanager]

  generator:
    build: ./generator
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      # Apunta al nombre del servicio BDD y su puerto INTERNO
      - STORAGE_SERVICE_URL=http://BDD:8000
    ports:
      - "8000:8000" # Puerto principal
    depends_on:
      - kafka
      - BDD

  llm:
    build: ./llm
    ports:
      - "8003:8003"
    environment:
      # Lee la clave desde el archivo .env
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - BOOTSTRAP_SERVERS=kafka:9092
      - LLM_MODEL=mock
    depends_on:
      - kafka

  retry-overload:
    build: ./retry
    command: python retry_overload.py
    environment:
    - BOOTSTRAP_SERVERS=kafka:9092
    depends_on: [kafka]

  retry-quota:
    build: ./retry
    command: python retry_quota.py
    environment:
    - BOOTSTRAP_SERVERS=kafka:9092
    depends_on: [kafka]

  # --- CORREGIDO ---
  # Renombrado de 'DataBase' a 'BDD' para que 'generator' lo encuentre
  BDD:
    build: ./BDD
    environment:
    - BOOTSTRAP_SERVERS=kafka:9092
    - DB_URL=sqlite:///data/data.db # Ruta dentro del volumen
    - SCORE_THRESHOLD=0.62
    volumes:
      # Monta el volumen en /app/data
      - storage_data:/app/data
    ports:
      - "8001:8000" # Puerto 8001 en el host, 8000 en el contenedor
    depends_on: [kafka]

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - kafka

volumes:
  storage_data: {}